"""
POD Shirt Designer -- kie.ai Pipeline
Generated by niche-skill-forge on 2026-05-16

End-to-end: prompt -> generate (native transparent) -> quality check -> export
Uses GPT-Image-2 via kie.ai API. No external dependencies.
kie.ai GPT-Image-2 returns true RGBA PNG via "background": "transparent" --
no background-removal post-processing step.

Usage:
    from pod_pipeline import PodPipeline
    pipe = PodPipeline(api_key="...")
    result = pipe.generate_shirt_design(
        prompt="...",
        name="my-design",
        aspect_ratio="3:4",
    )
"""

import os
import sys
import time
import json
from urllib.request import Request, urlopen
from urllib.error import HTTPError
from pathlib import Path


class PodPipeline:
    """Generate print-ready POD shirt designs via kie.ai GPT-Image-2."""

    API_BASE = "https://api.kie.ai/api/v1"
    PRINT_SUFFIX = (
        "isolated design element, no background, "
        "clean edges, bold outlines, print-ready t-shirt graphic"
    )

    def __init__(self, api_key: str | None = None, output_dir: str = "./out"):
        self.api_key = api_key or os.environ.get("KIE_API_KEY", "")
        if not self.api_key:
            raise ValueError("KIE_API_KEY not set")
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _request(self, method: str, path: str, body: dict | None = None,
                 timeout: int = 30) -> dict:
        url = f"{self.API_BASE}{path}"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        data = json.dumps(body).encode() if body else None
        req = Request(url, data=data, headers=headers, method=method)
        with urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode())

    def generate(self, prompt: str, aspect_ratio: str = "3:4",
                 resolution: str = "4K") -> dict:
        """Submit a generation task. Returns task info with taskId."""
        if "1:1" in aspect_ratio and resolution == "4K":
            resolution = "2K"

        full_prompt = f"{prompt}\n{self.PRINT_SUFFIX}"

        return self._request("POST", "/jobs/createTask", body={
            "model": "gpt-image-2-text-to-image",
            "input": {
                "prompt": full_prompt,
                "aspect_ratio": aspect_ratio,
                "resolution": resolution,
                "background": "transparent",
            }
        })

    def poll(self, task_id: str, interval: float = 5.0,
             max_wait: float = 600.0, log_fn=None) -> dict:
        """Poll until task completes or times out."""
        elapsed = 0.0
        while elapsed < max_wait:
            result = self._request("GET", f"/jobs/recordInfo?taskId={task_id}")
            status = result.get("data", {}).get("status", "")
            if log_fn:
                log_fn(f"  [{elapsed:.0f}s] status: {status}")
            if status in ("completed", "success", "done"):
                return result
            if status in ("failed", "error"):
                raise RuntimeError(f"Task {task_id} failed: {result}")
            time.sleep(interval)
            elapsed += interval
        raise TimeoutError(f"Task {task_id} timed out after {max_wait}s")

    def download(self, url: str, filename: str) -> Path:
        """Download image from URL to output directory."""
        path = self.output_dir / filename
        req = Request(url)
        with urlopen(req, timeout=60) as resp:
            path.write_bytes(resp.read())
        return path

    def generate_shirt_design(self, prompt: str, name: str,
                              aspect_ratio: str = "3:4",
                              resolution: str = "4K",
                              log_fn=None) -> dict:
        """Full pipeline: generate -> poll -> download -> return info."""
        log = log_fn or print

        log(f"Generating: {name}")
        log(f"  Aspect: {aspect_ratio}, Resolution: {resolution}")

        task = self.generate(prompt, aspect_ratio, resolution)
        task_id = task.get("data", {}).get("taskId", "")
        log(f"  Task ID: {task_id}")

        result = self.poll(task_id, log_fn=log)

        result_json = result.get("data", {}).get("resultJson", "")
        if isinstance(result_json, str):
            result_data = json.loads(result_json)
        else:
            result_data = result_json

        urls = result_data.get("resultUrls", [])
        if not urls:
            raise RuntimeError(f"No result URLs for task {task_id}")

        raw_path = self.download(urls[0], f"raw-{name}.png")
        log(f"  Downloaded: {raw_path}")

        cost = self.estimate_cost(aspect_ratio, resolution)
        log(f"  Estimated cost: {cost}")
        log(f"  Output is native RGBA (transparent). NEXT: run QC checklist, then resize/export")

        return {
            "task_id": task_id,
            "raw_path": str(raw_path),
            "image_url": urls[0],
            "cost_estimate": cost,
            "prompt_used": f"{prompt}\n{self.PRINT_SUFFIX}",
        }

    @staticmethod
    def estimate_cost(aspect_ratio: str = "3:4",
                      resolution: str = "4K") -> str:
        # Native transparency -> no background-removal cost (per v1.0.1 fix).
        base = 0.12 if resolution in ("1K", "2K") else 0.20
        return f"~${base:.2f} (generation, native transparent -- no bg removal)"


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python pod_pipeline.py <design-name> <prompt>")
        sys.exit(1)

    name = sys.argv[1]
    prompt = " ".join(sys.argv[2:])

    pipe = PodPipeline()
    result = pipe.generate_shirt_design(prompt=prompt, name=name)
    print(json.dumps(result, indent=2))
